name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.0.1
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets._GITHUB_PAT }}'

